"""Tests for Phase 12 — AI Assistant Layer (NVIDIA NIM / Nemotron 3.5 Lightning)."""

import json
from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

import pytest
from httpx import ASGITransport, AsyncClient

from app.config import settings
from app.main import app
from app.models import User
from app.scenarios.schema import (
    AIGenerateScenarioRequest,
    EstimatedImpact,
    ScenarioCategory,
    ScenarioDefinition,
    ScenarioSource,
    ScenarioTarget,
)
from app.services.ai_scenario_service import generate_scenario
from app.services.ai_service import AIService, ai_service
from app.services.auth_service import create_access_token


def test_ai_service_configuration():
    """Verify NVIDIA NIM configuration defaults."""
    assert settings.ai_provider == "nvidia_nim"
    assert settings.nvidia_nim_model == "nvidia/nemotron-3.5-lightning-30b-a3b"
    assert settings.nvidia_nim_base_url == "https://integrate.api.nvidia.com/v1"
    assert settings.nvidia_nim_enable_thinking is True
    assert ai_service.model == "nvidia/nemotron-3.5-lightning-30b-a3b"


def test_extract_json_dict_formats():
    """Verify JSON extraction handles raw JSON, markdown code blocks, and embedded objects."""
    # 1. Pure raw JSON
    raw = '{"name": "test", "concurrency": 10}'
    assert AIService._extract_json_dict(raw) == {"name": "test", "concurrency": 10}

    # 2. Markdown fenced code block
    fenced = """Here is the scenario definition:
```json
{
  "name": "SQL Injection Test",
  "category": "sql_injection",
  "concurrency": 5
}
```
Hope this helps!"""
    assert AIService._extract_json_dict(fenced) == {
        "name": "SQL Injection Test",
        "category": "sql_injection",
        "concurrency": 5,
    }

    # 3. Embedded JSON inside thoughts
    embedded = 'I will formulate this response: {"target": "/api/login", "method": "POST"} - end of thoughts.'
    assert AIService._extract_json_dict(embedded) == {"target": "/api/login", "method": "POST"}


@pytest.mark.asyncio
async def test_stream_chat_reasoning_and_content():
    """Test stream_chat splits reasoning deltas and content deltas."""
    service = AIService(api_key="mock-key", base_url="https://mock.api/v1")

    # Mock chunk structure from OpenAI SDK
    chunk1 = MagicMock()
    chunk1.choices = [MagicMock()]
    chunk1.choices[0].delta = MagicMock(reasoning_content="Thinking step 1...", content=None)

    chunk2 = MagicMock()
    chunk2.choices = [MagicMock()]
    chunk2.choices[0].delta = MagicMock(reasoning_content=None, content="Final answer text.")

    async def mock_generator():
        yield chunk1
        yield chunk2

    mock_client = MagicMock()
    mock_client.chat.completions.create = AsyncMock(return_value=mock_generator())

    with patch.object(service, "get_client", return_value=mock_client):
        chunks = []
        async for item in service.stream_chat(
            messages=[{"role": "user", "content": "Test prompt"}],
            enable_thinking=True,
        ):
            chunks.append(item)

        reasoning_chunks = [c for c in chunks if c["type"] == "reasoning"]
        content_chunks = [c for c in chunks if c["type"] == "content"]
        done_chunks = [c for c in chunks if c["type"] == "done"]

        assert len(reasoning_chunks) == 1
        assert reasoning_chunks[0]["delta"] == "Thinking step 1..."
        assert len(content_chunks) == 1
        assert content_chunks[0]["delta"] == "Final answer text."
        assert len(done_chunks) == 1
        assert done_chunks[0]["reasoning"] == "Thinking step 1..."
        assert done_chunks[0]["content"] == "Final answer text."


@pytest.mark.asyncio
async def test_generate_structured_with_validation():
    """Test generating a structured ScenarioDefinition via mocked AI service."""
    service = AIService(api_key="mock-key", base_url="https://mock.api/v1")

    valid_scenario_json = {
        "name": "NVIDIA NIM Generated Brute Force",
        "description": "Simulation generated by Nemotron 3.5 Lightning",
        "category": "brute_force",
        "target": {
            "service": "backend",
            "path": "/api/v1/auth/login",
            "port": 8080,
            "protocol": "http",
        },
        "method": "POST",
        "payload_category": "credential_guessing",
        "parameters": {"usernames": ["admin"], "wordlist_size": 20},
        "concurrency": 10,
        "duration": 30,
        "expected_signals": ["401 Unauthorized", "429 Too Many Requests"],
        "estimated_impact": "medium",
        "source": "ai",
    }

    with patch.object(
        service,
        "generate_chat",
        new=AsyncMock(
            return_value=(json.dumps(valid_scenario_json), "Reasoned through brute force model")
        ),
    ):
        model_instance, reasoning = await service.generate_structured(
            prompt="Generate a brute force attack",
            schema_class=ScenarioDefinition,
        )
        assert isinstance(model_instance, ScenarioDefinition)
        assert model_instance.category == ScenarioCategory.BRUTE_FORCE
        assert model_instance.target.path == "/api/v1/auth/login"
        assert reasoning == "Reasoned through brute force model"


@pytest.mark.asyncio
async def test_ai_scenario_service_generation_and_fallback():
    """Verify ai_scenario_service tries AI first and falls back safely on error."""
    org_id = uuid4()
    req = AIGenerateScenarioRequest(
        prompt="Simulate SQL injection against our search endpoint",
        category=ScenarioCategory.SQLI_RESILIENCE,
        target_path="/api/search",
    )

    # 1. Successful AI generation
    valid_scenario = ScenarioDefinition(
        name="AI SQLi Attack",
        description="Auto-generated SQLi",
        category=ScenarioCategory.SQLI_RESILIENCE,
        target=ScenarioTarget(path="/api/search", port=8080),
        method="GET",
        payload_category="sqli_resilience",
        parameters={"parameter_name": "q"},
        concurrency=12,
        duration=30,
        expected_signals=["SQL Syntax Error"],
        estimated_impact=EstimatedImpact.MEDIUM,
        source=ScenarioSource.AI,
    )

    with patch(
        "app.services.ai_scenario_service.ai_service.generate_structured",
        new=AsyncMock(return_value=(valid_scenario, "Thought about SQL injection vectors")),
    ):
        result = await generate_scenario(req, org_id)
        assert result.category == ScenarioCategory.SQLI_RESILIENCE
        assert result.source == ScenarioSource.AI
        assert result.concurrency == 12

    # 2. Failing AI generation triggers robust rule-based fallback
    with patch(
        "app.services.ai_scenario_service.ai_service.generate_structured",
        new=AsyncMock(side_effect=RuntimeError("NVIDIA NIM API timeout")),
    ):
        fallback_result = await generate_scenario(req, org_id)
        assert fallback_result is not None
        assert fallback_result.category == ScenarioCategory.SQLI_RESILIENCE
        assert fallback_result.source == ScenarioSource.AI
        assert fallback_result.target.path == "/api/search"


@pytest.mark.asyncio
async def test_ai_status_endpoint():
    """Verify GET /api/ai/status endpoint returns proper provider metadata."""
    org_id = uuid4()
    user_id = uuid4()
    token = create_access_token(
        user_id=user_id,
        email="security@pantheon.local",
        org_id=org_id,
        role="Admin",
    )

    # Mock get_current_user to avoid database hits during unit testing
    from app.services.auth_service import get_current_user

    test_user = User(
        id=user_id,
        email="security@pantheon.local",
        full_name="AI Security Engineer",
        hashed_password="hash",
        org_id=org_id,
        role="Admin",
        is_active=True,
    )
    app.dependency_overrides[get_current_user] = lambda: test_user

    try:
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            response = await client.get(
                "/api/ai/status",
                headers={"Authorization": f"Bearer {token}"},
            )
            assert response.status_code == 200
            data = response.json()
            assert data["provider"] == "nvidia_nim"
            assert data["model"] == "nvidia/nemotron-3.5-lightning-30b-a3b"
            assert data["thinking_enabled"] is True
            assert data["configured"] is True
    finally:
        app.dependency_overrides.pop(get_current_user, None)
